version: "3"
services:
  influxdb:
    image: influxdb:2.3
    volumes:
      - /tmp/testdata/influx:/var/lib/influxdb2:rw  # map where data and config files are stored
    ports:
      - "8086:8086"

  influxdb-cli:
    links:
      - influxdb
    image: influxdb:2.3
    volumes:
      - /tmp/testdata/influx:/var/lib/influxdb2:rw  # map where data and config files are stored
    entrypoint: ["influx", "setup", "--skip-verify", "-f", "-u", "admin", "-p", "influxdb-admin", "-o", "daveshep.net.nz", "-b", "fermenter-temperature", "--host=http://influxdb:8086"]
    restart: on-failure
    depends_on:
      - influxdb

