version: "3"
services:
  influxdb:
    image: influxdb:alpine
    volumes:
      - $PWD/config:/etc/influxdb2:rw
      - $PWD/data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - mynet

  data-generator:
    build: .
    command: python3 write_data_to_influxdb.py
    depends_on:
      - influxdb
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

